### PR TITLE
feat: add `targetPlatform` field

### LINKED ISSUE #19: Feature Request: Platform Selection
I'm on Linux and I'm trying to install the C++ extension, but it keeps selecting the Windows VSIX.

### PR DESCRIPTION
**Pull request by SylvKT**
Fixes #19

### CODE REVIEW

**Comment by daiyam** [comment]
Thanks for the PR.

But can you automatically detect the targetPlatform?

You can use `import { platform, arch } from 'process';` then translate it to VSCode's `TargetPlatform`
```
export const enum TargetPlatform {
	WIN32_X64 = 'win32-x64',
	WIN32_ARM64 = 'win32-arm64',

	LINUX_X64 = 'linux-x64',
	LINUX_ARM64 = 'linux-arm64',
	LINUX_ARMHF = 'linux-armhf',

	ALPINE_X64 = 'alpine-x64',
	ALPINE_ARM64 = 'alpine-arm64',

	DARWIN_X64 = 'darwin-x64',
	DARWIN_ARM64 = 'darwin-arm64',

	WEB = 'web',

	UNIVERSAL = 'universal',
	UNKNOWN = 'unknown',
	UNDEFINED = 'undefined',
}
```

The `platform` and `arch` are the same as node's arch

**Comment by daiyam** [comment]
@SylvKT Tell me if you can do the modifications. Thx

**Comment by SylvKT** [comment]
Ah, sorry; I completely forgot about this PR. I'll fix it tomorrow probably.

**Comment by daiyam** [comment]
No problem

**Comment by tomByrer** [comment]
@SylvKT ?

**Comment by daiyam** [comment]
The new version with the feature should be available.

**Pull request merged**
